[package]
name = "error_handling_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# 本示例没有外部依赖，如果使用 anyhow 或 thiserror，在此处添加
# anyhow = "1.0"
# thiserror = "1.0"
